version: '3'

services:
  sqlserver:
    container_name: mssql-csharp-tutorial
    environment:
      - ACCEPT_EULA=1
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=SQLConnect1
      - MSSQL_PID=Developer
    build: 
      context: ./db_initializer
      args:
        - ACCEPT_EULA=$ACCEPT_EULA
        - MSSQL_USER=$MSSQL_USER
        - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
        - MSSQL_PID=$MSSQL_PID
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U ${MSSQL_USER} -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 90s # the initialization script only starts after 60s and we have to wait a bit until if finishes

  dotnet-api:
    build: ./DotnetAPI
    ports:
      - 5000:5000
    depends_on:
      - sqlserver

volumes:
  sqlserver_data: